name:               "Haizhu.Pan"
description:        "A personal blog (using Ink's theme)"

url:                ""
author:             "haizhupan"
email:              "haizhupan@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
email:              "haizhupan@gmail.com"
github:             "haizhupan"

disqus_shortname:   "thinker3197"

background:         "http://www.hdiphone6wallpaper.com/wp-content/uploads/Nature/FTP2/Blue sky wind turbines iphone 6 wallpaper.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Pictures"
    href:           "/pictures"
  - name:           "Publications"
    href:           "/publish"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
