name:               "数分学长"
description:        "一枚最不像数分师的数据分析师"

url:                "https://carrylaw.github.io/"
author:             "Carry.law"
email:              "hbwhfeifei@qq.com"
gravatar_hash:      ""
twitter:            ""
email:              "hbwhfeifei@qq.com"
github:             "https://carrylaw.github.io/"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "Carry"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "about"
  - name:           "Download"
    href:           "releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
